version: '3.8'

services:
  inventory:
    build: ./inventory
    container_name: inventory_service
    networks:
      - microservices-net

  payment:
    build: ./payment
    container_name: payment_service
    networks:
      - microservices-net

  order:
    build: ./order
    container_name: order_service
    networks:
      - microservices-net

  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy_lb
    ports:
      - "8000:8000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - inventory
      - order
      - payment
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
